//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAYER_ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int IdMantenimiento { get; set; }
        public int IdVehiculo { get; set; }
        public string Tarea { get; set; }
        public int IdEmpleado { get; set; }
        public int Valor { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaEstFin { get; set; }
        public bool IsPago { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
